In [2]:
import numpy as np

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
print(np.__version__)

2.4.2


In [5]:
import numpy as np

np.random.seed(42)
scores = np.random.randint(50, 101, size=(5, 4))

scores

array([[88, 78, 64, 92],
       [57, 70, 88, 68],
       [72, 60, 60, 73],
       [85, 89, 73, 52],
       [71, 51, 73, 93]], dtype=int32)

In [6]:
scores[2, 1]

np.int32(60)

In [7]:
scores[-2:, :]

array([[85, 89, 73, 52],
       [71, 51, 73, 93]], dtype=int32)

In [8]:
scores[:3, 1:3]

array([[78, 64],
       [70, 88],
       [60, 60]], dtype=int32)

In [9]:
column_mean = np.round(scores.mean(axis=0), 2)
column_mean

array([74.6, 69.6, 71.6, 75.6])

In [10]:
curve = np.array([5, 3, 7, 2])
curved_scores = scores + curve
curved_scores

array([[93, 81, 71, 94],
       [62, 73, 95, 70],
       [77, 63, 67, 75],
       [90, 92, 80, 54],
       [76, 54, 80, 95]])

In [11]:
curved_scores = np.clip(curved_scores, None, 100)
curved_scores

array([[93, 81, 71, 94],
       [62, 73, 95, 70],
       [77, 63, 67, 75],
       [90, 92, 80, 54],
       [76, 54, 80, 95]])

In [12]:
row_max = curved_scores.max(axis=1)
row_max

array([94, 95, 77, 92, 95])

In [13]:
row_min = curved_scores.min(axis=1, keepdims=True)
row_max = curved_scores.max(axis=1, keepdims=True)

normalized = (curved_scores - row_min) / (row_max - row_min)

normalized

array([[0.95652174, 0.43478261, 0.        , 1.        ],
       [0.        , 0.33333333, 1.        , 0.24242424],
       [1.        , 0.        , 0.28571429, 0.85714286],
       [0.94736842, 1.        , 0.68421053, 0.        ],
       [0.53658537, 0.        , 0.63414634, 1.        ]])

In [14]:
max_index = np.unravel_index(np.argmax(normalized), normalized.shape)
max_index

(np.int64(0), np.int64(3))

In [15]:
above_90 = curved_scores[curved_scores > 90]
above_90

array([93, 94, 95, 92, 95])